### ISSUE TITLE
YAML Sync Error

### ISSUE THREAD

**Issue by SwiseWeb** [barrelstrength/craft-sprout-seo#213]
Not sure if this is related to #210 or not, but we have been experiencing issues when trying to sync new sections across environments via the project.yaml file. This issue seems to come up when entry types in those sections have a Sprout SEO Metadata field associated with them. To try to narrow down the issue, I just went through the following steps:

1. Created a new Craft site from scratch
2. Added one single called ‘Homepage’
3. Installed Sprout SEO
4. Created Sprout Metadata field and added it to the Homepage single layout
5. Enabled the project.yaml file
6. Created a git repo and committed all files
7. Deleted the Homepage single in the Craft admin panel
8. Checked out the YAML file from git (`git checkout config/project.yaml`)
9. Ran `./craft project-config/sync`
10. Got the following error: `error: Invalid argument supplied for foreach()`
11. Homepage single in the Craft admin panel now has entry types (0)

Further inspection of the console.log file shows the following stacktrace:
```
2020-05-21 16:37:54 [-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in /Users/Shared/Development/Sites/sprout-test/vendor/barrelstrength/sprout-base-uris/src/models/UrlEnabledSection.php:149
Stack trace:
#0 /Users/Shared/Development/Sites/sprout-test/vendor/barrelstrength/sprout-base-uris/src/models/UrlEnabledSection.php(149): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/Users/Shared/D...', 149, Array)
#1 /Users/Shared/Development/Sites/sprout-test/vendor/barrelstrength/sprout-seo/src/services/ElementMetadata.php(309): barrelstrength\sproutbaseuris\models\UrlEnabledSection->hasFieldLayoutId(1)
#2 /Users/Shared/Development/Sites/sprout-test/vendor/barrelstrength/sprout-seo/src/services/ElementMetadata.php(121): barrelstrength\sproutseo\services\ElementMetadata->resaveElementsByUrlEnabledSection('craft\\elements\\...', true, Object(craft\models\FieldLayout))
#3 /Users/Shared/Development/Sites/sprout-test/vendor/barrelstrength/sprout-seo/src/SproutSeo.php(144): barrelstrength\sproutseo\services\ElementMetadata->resaveElementsAfterFieldLayoutIsSaved(Object(craft\events\FieldLayoutEvent))
#4 [internal function]: barrelstrength\sproutseo\SproutSeo::barrelstrength\sproutseo\{closure}(Object(craft\events\FieldLayoutEvent))
#5 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\FieldLayoutEvent))
#6 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveFieldL...', Object(craft\events\FieldLayoutEvent))
#7 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/Fields.php(1320): yii\base\Component->trigger('afterSaveFieldL...', Object(craft\events\FieldLayoutEvent))
#8 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/Sections.php(1226): craft\services\Fields->saveLayout(Object(craft\models\FieldLayout))
#9 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#11 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#12 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#13 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\ProjectConfig->processConfigChanges('sections.35f732...')
#14 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#15 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#16 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#17 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/ProjectConfig.php(1204): craft\services\ProjectConfig->processConfigChanges('sections.35f732...', false, NULL, true)
#18 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/services/ProjectConfig.php(539): craft\services\ProjectConfig->_applyChanges(Array)
#19 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#20 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#21 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('sync', Array)
#24 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('sync', Array)
#25 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#26 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#27 /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#28 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#29 /Users/Shared/Development/Sites/sprout-test/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#30 /Users/Shared/Development/Sites/sprout-test/craft(23): yii\base\Application->run()
#31 {main}
```

Craft Version: 3.4.20
Sprout SEO Version: 4.6.1

**Comment by BenParizek** [comment]
@SwiseWeb I've just released Sprout SEO v4.6.3 which I believe will resolve this. Let me know if you continue to run into any issues.

**Comment by SwiseWeb** [comment]
@BenParizek this is great, thank you! I did notice that after the update, when running step 9 in the above steps, I still get this error: 
```
2020-05-22 15:20:37 [-][-][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Section 1 has no entry types in /Users/Shared/Development/Sites/sprout-test/vendor/craftcms/cms/src/elements/Entry.php:881
```
Despite the error, everything seems to have synced just fine and if I run the project config sync a second time, everything runs through without an issue. Is this an order of operations issue with how Craft and Sprout are interacting? Is there anything that could or should be done about that initial error?

**Comment by BenParizek** [comment]
@SwiseWeb The error you are seeing ther has nothing to do with Sprout now. That's just Craft's Entry Element telling you that one of your sections doesn't have any Entry Types:
https://github.com/craftcms/cms/blob/3.4.20/src/elements/Entry.php#L881

I believe the issue was simply that our code wasn't taking into account the scenario where you have a section without Entry Types. The reason the sync was failing is because Craft's Project Config manages all of those Section settings so when Sprout's code was expecting an Entry Type to have a Field Layout and no Entry Type existed, Craft's resaving of the Section failed causing the Project Config to fail to sync.
